version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - goconst
  settings:
    goconst:
      min-occurrences: 3
  exclusions:
    max-issues-per-linter: 20
    max-same-issues: 5
    rules:
      - path: _test\.go
        linters:
          - errcheck
