run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goconst

linters-settings:
  goconst:
    min-occurrences: 3

issues:
  max-issues-per-linter: 20
  max-same-issues: 5
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
